services:
  - name: api-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o api ./cmd/api
    startCommand: ./api
    envVars:
      - key: API_URL
        value: "https://api-service-ub0y.onrender.com"

  - name: backend-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o backend ./cmd/backend
    startCommand: ./backend
    envVars:
      - key: BACKEND_URL
        value: "https://backend-service-mjv8.onrender.com"

  - name: aiservice-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o aiservice ./cmd/aiservice
    startCommand: ./aiservice
    envVars:
      - key: AI_URL
        value: "https://aiservice-service.onrender.com"

  - name: evaluation-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o evaluation ./cmd/evaluation
    startCommand: ./evaluation
    envVars:
      - key: EVAL_URL
        value: "https://evaluation-service-dytd.onrender.com"

  - name: highlight-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o highlight ./cmd/highlight
    startCommand: ./highlight
    envVars:
      - key: HIGHLIGHT_URL
        value: "https://highlight-service.onrender.com"

  - name: output-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o output ./cmd/output
    startCommand: ./output
    envVars:
      - key: OUTPUT_URL
        value: "https://output-service.onrender.com"

  - name: parsing-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o parsing ./cmd/parsing
    startCommand: ./parsing
    envVars:
      - key: PARSE_URL
        value: "https://parsing-service.onrender.com"

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: cd webs && npm install && npm run build
    startCommand: cd webs && npm install -g serve && serve -s dist
