services:
  - name: api-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o api ./cmd/api
    startCommand: ./api

  - name: backend-service
    type: web
    env: go
    plan: free
    buildCommand: go build -o backend ./cmd/backend
    startCommand: ./backend

  - name: frontend
    type: web
    env: node
    plan: free
    buildCommand: cd webs && npm install
    startCommand: cd webs && npm run dev
